apiVersion: v1
kind: Pod
metadata:
  name: resource-request-pod
  labels:
    app: resource-request-pod
spec:
  containers:
  - name: webapp
    image: kodekloud/webapp-color
    env:
    - name: bitch
      value: sup
    - name: myname
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: name
        
    envFrom:
    - secretRef:
        name: my-secret
    # resources:
    #   requests:
    #     memory: "120Mi"
    #     cpu: "120m"
    #   limits:
    #     memory: "120Mi"
    #     cpu: "120m"