apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 9.5.12
      chart: argo-cd
      helm:
        valueFiles:
          - $values/values/argocd/values.yaml
    - repoURL: git@github.com:dakotajbuckley/kubernetes-configurations.git
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true