apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-basic
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 29.2.1
    chart: prometheus
    helm:
      parameters:
        - name: crds.enabled
          value: "true"
      values: |
        alertmanager:
          enabled: false
        prometheus-pushgateway:
          enabled: false
        extraScrapeConfigs: |
          - job_name: 'federate-secondary'
            scrape_interval: 30s
            honor_labels: true
            metrics_path: /federate
            params:
              'match[]':
                - 'up'
                - '{job=~".+"}'
            static_configs:
              - targets:
                  - 'prometheus-secondary-server.monitoring-secondary.svc.cluster.local:80'
                labels:
                  cluster: 'secondary-sim'

  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-primary
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true