apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-secondary
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 29.2.1
      helm:
        releaseName: prometheus-secondary
        valueFiles:
          - $values/values/prometheus-secondary/values.yaml
    - repoURL: git@github.com:dakotajbuckley/kubernetes-configurations.git
      targetRevision: main
      ref: values


  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-secondary

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true