apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-resource-constraint
spec:
  limits:
    - type: Container
      default:
        cpu: "100m"
        memory: "100Mi"
      defaultRequest:
        cpu: "50m"
        memory: "50Mi"
      min:
        cpu: "20m"
        memory: "20Mi"
      max:
        cpu: "200m"
        memory: "200Mi"