sources:
  - service
  - ingress

policy: upsert-only
registry: txt
txtOwnerId: local-cluster

domainFilters:
  - dakotabuilds.dev

provider:
  name: azure

extraVolumes:
  - name: azure-config-file
    secret:
      secretName: azure-config-file

extraVolumeMounts:
  - name: azure-config-file
    mountPath: /etc/kubernetes
    readOnly: true
