apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-chart
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
  selector:
    app: nginx-chart
  type: NodePort