apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: {{ .Values.appname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      name: nginx-chart
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
        - name: {{ .Values.image.repository }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}