apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example-secret
  namespace: external-secrets
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: dakotabuilds-kv
    kind: ClusterSecretStore
  target:
    name: example-secret
    creationPolicy: Owner
  data:
  - secretKey: favorite-food
    remoteRef:
      key: favorite-food